parameters:
    gm_ez_fixtures.context.initializer.class: GMaissa\eZFixturesExtension\Context\Initializer\ContextInitializer

services:
    gm_ez_fixtures.context.initializer:
        class: "%gm_ez_fixtures.context.initializer.class%"
        arguments:
            - "%behat.gm_ezfixtures_extension.fixtures_base_dir%"
        tags:
           - { name: context.initializer }
